### PR TITLE
[add-values-manifest] add values file

### PR DESCRIPTION
**Pull request by aliartiza75**

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-29/1/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-29/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-29/3/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-29/4/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-29/5/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-29/6/) has Failed!

**Review by ahmedwaleedmalik — APPROVED** [review]

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-29/7/) has Failed!

**Pull request merged**
