### PR TITLE
add-tracing Add tracing

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-25/1/) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-25/2/) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-25/3/) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-25/4/) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-cart/job/PR-25/5/) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-25-6-SNAPSHOT`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-25-7-SNAPSHOT`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-25-8-SNAPSHOT`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-25-9-SNAPSHOT`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-25-10-SNAPSHOT`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-25-11-SNAPSHOT`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-25-12-SNAPSHOT`

**Review by kahootali — DISMISSED** [review]

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-25-13-SNAPSHOT`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
