### PR TITLE
[add-labels] add label

### PR DESCRIPTION
**Pull request by aliartiza75**

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-35-1-SNAPSHOT`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-35-2-SNAPSHOT`

**Review by ahmedwaleedmalik — APPROVED** [review]

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-35-3-SNAPSHOT`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/cart:0.0.0-PR-35-4-SNAPSHOT`

**Pull request merged**
