### PR TITLE
Add unit test for Istio Header

### PR DESCRIPTION
**Pull request by hamza3202**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hamza3202 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-8/1/) has Failed!

**Comment by stakater-user** [comment]
@hamza3202 Image is available for testing. `docker pull docker-release.workshop.stakater.com:443/stakater/cart:SNAPSHOT-PR-8-1`

**Comment by stakater-user** [comment]
@hamza3202 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-8/2/) has Failed!

**Comment by stakater-user** [comment]
@hamza3202 Image is available for testing. `docker pull docker-release.workshop.stakater.com:443/stakater/cart:SNAPSHOT-PR-8-2`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
