### PR TITLE
[update-pipeline-lib-version-to-2.16.11] update pipeline library version

### PR DESCRIPTION
**Pull request by aliartiza75**

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-18/1/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins-delivery.workshop.stakater.com/job/Stakater%20Nordmart/job/stakater-nordmart-cart/job/PR-18/1/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-18/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins-delivery.workshop.stakater.com/job/Stakater%20Nordmart/job/stakater-nordmart-cart/job/PR-18/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins-delivery.workshop.stakater.com/job/Stakater%20Nordmart/job/stakater-nordmart-cart/job/PR-18/3/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-18/3/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins-delivery.workshop.stakater.com/job/Stakater%20Nordmart/job/stakater-nordmart-cart/job/PR-18/4/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-18/4/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins-delivery.workshop.stakater.com/job/Stakater%20Nordmart/job/stakater-nordmart-cart/job/PR-18/5/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins-delivery.workshop.stakater.com/job/Stakater%20Nordmart/job/stakater-nordmart-cart/job/PR-18/6/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins-delivery.workshop.stakater.com/job/Stakater%20Nordmart/job/stakater-nordmart-cart/job/PR-18/7/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 8](https://jenkins-delivery.workshop.stakater.com/job/Stakater%20Nordmart/job/stakater-nordmart-cart/job/PR-18/8/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 9](https://jenkins-delivery.workshop.stakater.com/job/Stakater%20Nordmart/job/stakater-nordmart-cart/job/PR-18/9/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/3/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-18/6/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/4/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/5/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-18/7/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/6/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/7/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 8](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/8/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/3/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/4/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/5/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-cart/job/PR-18/6/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-delivery.workshop.stakater.com:443/stakater-lab/cart:0.0.0-PR-18-7-SNAPSHOT`

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 8](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-18/8/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-delivery.workshop.stakater.com:443/stakater-lab/cart:0.0.0-PR-18-8-SNAPSHOT`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
