### PR TITLE
[update-jenkins-config]

### PR DESCRIPTION
**Pull request by aliartiza75**
update Jenkins config

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-17/1/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-17/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-17/3/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stackator.com:443/stakater-lab/cart:0.0.0-PR-17-4-SNAPSHOT`

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-cart/job/PR-17/4/) has Failed!

**Review by kahootali — APPROVED** [review]

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stackator.com:443/stakater-lab/cart:0.0.0-PR-17-5-SNAPSHOT`

**Pull request merged**
