### PR TITLE
added chart folder

### PR DESCRIPTION
**Pull request by hanzala1234**

### CODE REVIEW

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus.openshift-stakater-nexus.svc.cluster.local:5003/repository/docker/stakater-nordmart-cart:SNAPSHOT-PR-39-0bb4a57c` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus.openshift-stakater-nexus.svc.cluster.local:5003/repository/docker/stakater-nordmart-cart:SNAPSHOT-PR-39-f800064c` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus.openshift-stakater-nexus.svc.cluster.local:5003/repository/docker/stakater-nordmart-cart:SNAPSHOT-PR-39-28666515` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus.openshift-stakater-nexus.svc.cluster.local:5003/repository/docker/stakater-nordmart-cart:SNAPSHOT-PR-39-5b4985cb` is available

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
