### PR TITLE
[e2e-tests]

### PR DESCRIPTION
**Pull request by aliartiza75**
update Jenkinsfile

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins-delivery.cp-stakater.com/job/NordMart%20Applications/job/stakater-nordmart-cart/job/PR-24/1/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins-delivery.cp-stakater.com/job/NordMart%20Applications/job/stakater-nordmart-cart/job/PR-24/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins-delivery.cp-stakater.com/job/NordMart%20Applications/job/stakater-nordmart-cart/job/PR-24/3/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins-delivery.cp-stakater.com/job/NordMart%20Applications/job/stakater-nordmart-cart/job/PR-24/4/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-delivery.cp-stakater.com:443/stakater-lab/cart:0.0.0-PR-24-5-SNAPSHOT`

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins-delivery.cp-stakater.com/job/NordMart%20Applications/job/stakater-nordmart-cart/job/PR-24/6/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-delivery.cp-stakater.com:443/stakater-lab/cart:0.0.0-PR-24-7-SNAPSHOT`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-delivery.cp-stakater.com:443/stakater-lab/cart:0.0.0-PR-24-8-SNAPSHOT`

**Review by kahootali — APPROVED** [review]

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-delivery.cp-stakater.com:443/stakater-lab/cart:0.0.0-PR-24-9-SNAPSHOT`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
